/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.artificialIntelligence;



import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class XMLReader {
    public static void main(String[] args) {
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse("path/to/your/file.xml");
            
            document.getDocumentElement().normalize();
            Element root = document.getDocumentElement();
            NodeList nodeList = root.getChildNodes();
            
            for (int i = 0; i < nodeList.getLength(); i++) {
                if (nodeList.item(i) instanceof Element) {
                    Element element = (Element) nodeList.item(i);
                    System.out.println("Field: " + element.getNodeName() + ", Value: " + element.getTextContent());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}



import java.util.Scanner;
import java.util.HashSet;
import java.util.Set;

public class XMLReader {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(System.in);
            Set<String> selectedFields = new HashSet<>();
            
            System.out.println("Enter fields to display (comma-separated): ");
            String[] fields = scanner.nextLine().split(",");
            for (String field : fields) {
                selectedFields.add(field.trim());
            }
            
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse("path/to/your/file.xml");
            
            document.getDocumentElement().normalize();
            Element root = document.getDocumentElement();
            NodeList nodeList = root.getChildNodes();
            
            for (int i = 0; i < nodeList.getLength(); i++) {
                if (nodeList.item(i) instanceof Element) {
                    Element element = (Element) nodeList.item(i);
                    if (selectedFields.contains(element.getNodeName())) {
                        System.out.println("Field: " + element.getNodeName() + ", Value: " + element.getTextContent());
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}


import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class XMLReader {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(System.in);
            Set<String> selectedFields = new HashSet<>();
            
            System.out.println("Enter fields to display (comma-separated): ");
            String[] fields = scanner.nextLine().split(",");
            for (String field : fields) {
                selectedFields.add(field.trim());
            }
            
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse("path/to/your/file.xml");
            
            document.getDocumentElement().normalize();
            Element root = document.getDocumentElement();
            NodeList nodeList = root.getChildNodes();
            
            ObjectMapper mapper = new ObjectMapper();
            ObjectNode jsonNode = mapper.createObjectNode();
            
            for (int i = 0; i < nodeList.getLength(); i++) {
                if (nodeList.item(i) instanceof Element) {
                    Element element = (Element) nodeList.item(i);
                    if (selectedFields.contains(element.getNodeName())) {
                        jsonNode.put(element.getNodeName(), element.getTextContent());
                    }
                }
            }
            
            String jsonString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonNode);
            System.out.println(jsonString);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

import java.util.InputMismatchException;

public class XMLReader {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(System.in);
            Set<String> selectedFields = new HashSet<>();
            
            System.out.println("Enter fields to display (comma-separated): ");
            String[] fields = scanner.nextLine().split(",");
            if (fields.length == 0) {
                throw new InputMismatchException("No fields entered.");
            }
            for (String field : fields) {
                if (field.trim().isEmpty()) {
                    throw new InputMismatchException("Field name cannot be empty.");
                }
                selectedFields.add(field.trim());
            }
            
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse("path/to/your/file.xml");
            
            document.getDocumentElement().normalize();
            Element root = document.getDocumentElement();
            NodeList nodeList = root.getChildNodes();
            
            ObjectMapper mapper = new ObjectMapper();
            ObjectNode jsonNode = mapper.createObjectNode();
            
            for (int i = 0; i < nodeList.getLength(); i++) {
                if (nodeList.item(i) instanceof Element) {
                    Element element = (Element) nodeList.item(i);
                    if (selectedFields.contains(element.getNodeName())) {
                        jsonNode.put(element.getNodeName(), element.getTextContent());
                    }
                }
            }
            
            String jsonString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonNode);
            System.out.println(jsonString);
        } catch (InputMismatchException e) {
            System.out.println("Input error: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}


import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import java.util.Set;
import java.util.HashSet;
import java.util.Scanner;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class SAXXMLReader {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(System.in);
            Set<String> selectedFields = new HashSet<>();
            
            System.out.println("Enter fields to display (comma-separated): ");
            String[] fields = scanner.nextLine().split(",");
            for (String field : fields) {
                selectedFields.add(field.trim());
            }
            
            SAXParserFactory factory = SAXParserFactory.newInstance();
            SAXParser saxParser = factory.newSAXParser();
            SAXHandler handler = new SAXHandler(selectedFields);
            
            saxParser.parse("path/to/your/file.xml", handler);
            
            ObjectMapper mapper = new ObjectMapper();
            String jsonString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(handler.getJsonNode());
            System.out.println(jsonString);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

class SAXHandler extends DefaultHandler {
    private Set<String> selectedFields;
    private ObjectNode jsonNode;
    private String currentElement;

    public SAXHandler(Set<String> selectedFields) {
        this.selectedFields = selectedFields;
        this.jsonNode = new ObjectMapper().createObjectNode();
    }

    public ObjectNode getJsonNode() {
        return jsonNode;
    }

    @Override
    public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException {
        currentElement = qName;
    }

    @Override
    public void characters(char[] ch, int start, int length) throws SAXException {
        if (currentElement != null && selectedFields.contains(currentElement)) {
            jsonNode.put(currentElement, new String(ch, start, length));
        }
    }

    @Override
    public void endElement(String uri, String localName, String qName) throws SAXException {
        currentElement = null;
    }
}
